### ISSUE TITLE
Добавить meta viewport в index.html

### ISSUE THREAD

**Issue by Vladimir-Suetin** [zuhijan/cohort46#10]
[[enhancement]](https://github.com/zuhijan/cohort46/labels/enhancement)
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

**Comment by zuhijan** [comment]
Привет, хорошая идея, поддерживаю.

Теперь любой может взять этот вопрос сделать пул-реквест и решить этот момент.

Единственное правило: 
Нужно отписаться, что берете issue - и сделать отдельный пул реквест с решением, со слылкой на issue.

**Comment by YuryAmonsky** [comment]
Отписаться нужно здесь в коментах?

**Comment by zuhijan** [comment]
@YuryAmonsky да, что взялся за этот ишью - чтобы  несколько человек одновроменно двойную работу не делали.

**Comment by Vladimir-Suetin** [comment]
Я взялся и уже отправил

**Comment by zuhijan** [comment]
добавлено
https://github.com/zuhijan/cohort46/pull/11
