### ISSUE TITLE
Добавить .editorconfig

### ISSUE THREAD

**Issue by zuhijan** [zuhijan/cohort46#12]
Необходимо добавить файл  .editorconfig.
Каждое правило должно быть помечено комментарием - объясняющим его.

Так как мы учимся - в начале файла должен быть комментарий - объясняющий: зачем этот файл, какую пользу он несет и как убедиться, что он работает.

**Comment by Vladimir-Suetin** [comment]
сейчас попробую сделать

**Comment by Vladimir-Suetin** [comment]
Привет! Я отправил editorconfig #13

**Comment by zuhijan** [comment]
https://github.com/zuhijan/cohort46/pull/13 добавлено
